# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raymond Chou
email: >
description: > # this means to ignore newlines until "baseurl:"
  Raymond Chou's Design Portfolio
baseurl: "/Design-Portfolio" # the subpath of your site, e.g. /blog
url: "https://raymond3chou.github.io" # the base hostname & protocol for your site
twitter_username: > 
github_username:  raymond3chou
# Build settings
markdown: kramdown
